### ISSUE TITLE
RSS Feed Link

### ISSUE THREAD

**Issue by jmar777** [darkwing/blog#17]
Running OSX Mountain Lion + Chrome

Clicking the RSS feed link seems to do some pushState() magic resulting in http://davidwalsh.name/feed in the URL, but the user is actually greeted with a new page that contains only sidebar content.  Clicking the RSS feed link again from the new page actually takes the user to the "real" http://davidwalsh.name/feed.

**Comment by darkwing** [comment]
Awesome catch, will be on next build.
