### ISSUE TITLE
The right sidebar doesnt load with ABP enabled

### ISSUE THREAD

**Issue by jimaek** [darkwing/blog#2]
With Firefox and ABP the right sidebar is not loading at all.
Also the "Post Archive" link on the bottom almost crashed by browser with the google script going unresponsive as it loaded all of your posts on one page.

This is the major things I noticed.
Great job on the website!

**Comment by darkwing** [comment]
What is ABP?

**Comment by jimaek** [comment]
Sorry. AdBlockPlus

**Comment by darkwing** [comment]
Weird;  OK, I'll keep it in mind.  Is there any error in the console or anything?

**Comment by jimaek** [comment]
Nope, but here is the list with the blocked resources. I forgot to say that I'm subscribed to a list that blocks all social buttons. But still I don't see the connection between them and the loading of the whole sidebar.

##.twitter
http://apis.google.com/js/plusone.js
http://assets.pinterest.com/js/pinit.js?13498086462020
http://assets.pinterest.com/js/pinit.js?13498086462051
http://assets.pinterest.com/js/pinit.js?13498086462072
http://assets.pinterest.com/js/pinit.js?13498086462103
http://assets.pinterest.com/js/pinit.js?13498086462124
http://davidwalsh.name/wp-content/themes/jack/js/ads.js
http://davidwalsh.name/wp-content/themes/jack/js/analytics.js
http://facebook.com/plugins/like.php?href=http://davidwalsh.name/confessions-xii&send=true&layout=button_count&width=80&show_faces=false&action=like&colorscheme=light&height=21&&appId=118237474872582
http://facebook.com/plugins/like.php?href=http://davidwalsh.name/fokus&send=true&layout=button_count&width=80&show_faces=false&action=like&colorscheme=light&height=21&&appId=118237474872582
http://facebook.com/plugins/like.php?href=http://davidwalsh.name/html5-apis&send=true&layout=button_count&width=80&show_faces=false&action=like&colorscheme=light&height=21&&appId=118237474872582
http://facebook.com/plugins/like.php?href=http://davidwalsh.name/relaunch&send=true&layout=button_count&width=80&show_faces=false&action=like&colorscheme=light&height=21&&appId=118237474872582
http://facebook.com/plugins/like.php?href=http://davidwalsh.name/retina-favicons&send=true&layout=button_count&width=80&show_faces=false&action=like&colorscheme=light&height=21&&appId=118237474872582
http://google-analytics.com/ga.js
http://platform.twitter.com/widgets.js

**Comment by darkwing** [comment]
I'm going to close this for now;  I don't want to make loads of adjustments to accommodate browser plugins.
