### ISSUE TITLE
demoBox doesn't gets reset

### ISSUE THREAD

**Issue by welovewebdesign** [darkwing/blog#21]
- On a demo page like this one: http://davidwalsh.name/demo/folding-animation.php
- When clicking the "click here to view more demos!" link on top
- A list of demo's links appear but the demoBox doesn't gets reset.

![](https://dl.dropbox.com/u/25560/Untitled-1.jpg)

**Comment by darkwing** [comment]
Yuck.  Good catch! I'll work on getting that fixed!

**Comment by darkwing** [comment]
Fixed, I forgot to upload the correct example files...
