### ISSUE TITLE
AZ in your footer

### ISSUE THREAD

**Issue by nitishdhar** [darkwing/blog#25]
Hey, there is a string AZ lying at the bottom. Unless its required, I guess its an issue.

**Comment by nitishdhar** [comment]
I guess you fixed it.. I must have seen something while you were working on it..

**Comment by nitishdhar** [comment]
Nope its still there - http://davidwalsh.name/css-box-shadow

**Comment by darkwing** [comment]
Just found where it lived -- fixed in new build which will be pushed later today.
