### ISSUE TITLE
Social div overflow

### ISSUE THREAD

**Issue by alterphp** [darkwing/blog#32]
Hi !

screenshot : http://img4.hostingpics.net/pics/871321socialdivoverflow.png

I guess I see that bug cause I'm french and "Like" button is translated into "J'aime"... So the number of likes is partially hidden cause of combination of fixed width (80px) and hidden overflow on div.social... I think you don't need both properties and making a choice will solve that.

I understand fixed width on G+ and Twitter button (you want to control spacing from iframe), so I would delete overflow property or increase fixed width.

Cheers,

**Comment by darkwing** [comment]
Thanks for the report!

**Comment by darkwing** [comment]
Updated width, will be updated with the next push.
