### ISSUE TITLE
On Chrome 23 with Linux, the entire screen turns black after page has finished loading.

### ISSUE THREAD

**Issue by joshuataylor** [darkwing/blog#37]
On Chrome 23 with Linux, the entire screen turns black after page has finished loading.

**Comment by darkwing** [comment]
Weird;  obviously a CSS transform / opacity issue.

**Comment by joshuataylor** [comment]
Seems that either a site update or chrome update fixed this. Tested on my home desktop and works fine (same issue was occuring on multiple machines with Chrome 23/Ubuntu).
