### ISSUE TITLE
rss feed icon as appearing on top of Page header

### ISSUE THREAD

**Issue by qaiser110** [darkwing/blog#38]
http://davidwalsh.name/documentfragment

**Comment by darkwing** [comment]
Can you get me a screenshot, and tell me what platform and browser you're using?

**Comment by qaiser110** [comment]
I'm using chrome 23 on Windows 7. Here's the screenshot:
[image: Inline image 1]

**Comment by darkwing** [comment]
Unfortunately I'm not seeing the screenshot (?)

**Comment by qaiser110** [comment]
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=15_11_12_
Eddie_emailLanding_InviteContact_a&emailTemplate=email_InviteContact_a&emailTheme
=30_10_12_Eddie_email_InviteContact_a_InviteContact&user=0f519f62-1861-e211-bb20-
b4fd0eafa145&signedParameters=PzyrEfS-FgEOx0vDmiZpACdfnqs4SfSZYWRgyS8uaXk.eyJlbWF
pbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0
LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xODYxLWUyMTEtYmIyMC1iN
GZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMDFiMjgwOTI1ZSIsImlzc3
VlZF9hdCI6IjEzNTg0NzY4NTciLCJ2ZXIiOiIxIn0&emailMessageId=6ced6f75-1861-e211-8620-
f28df699edf6&emailType=Invite&emailLinkType=Logo&sdate=201301180240&utm_source=Em
ailInvite&utm_medium=Email>

Hi,

Become a part of your friend's network.

<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=15_11_12_
Eddie_emailLanding_InviteContact_a&emailTemplate=email_InviteContact_a&emailTheme
=30_10_12_Eddie_email_InviteContact_a_InviteContact&user=0f519f62-1861-e211-bb20-
b4fd0eafa145&signedParameters=PzyrEfS-FgEOx0vDmiZpACdfnqs4SfSZYWRgyS8uaXk.eyJlbWF
pbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0
LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xODYxLWUyMTEtYmIyMC1iN
GZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMDFiMjgwOTI1ZSIsImlzc3
VlZF9hdCI6IjEzNTg0NzY4NTciLCJ2ZXIiOiIxIn0&emailMessageId=6ced6f75-1861-e211-8620-
f28df699edf6&emailType=Invite&emailLinkType=ProfileThumb&sdate=201301180240&utm_s
ource=EmailInvite&utm_medium=Email>

Qaiser Abbas
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=15_11_12_
Eddie_emailLanding_InviteContact_a&emailTemplate=email_InviteContact_a&emailTheme
=30_10_12_Eddie_email_InviteContact_a_InviteContact&user=0f519f62-1861-e211-bb20-
b4fd0eafa145&signedParameters=PzyrEfS-FgEOx0vDmiZpACdfnqs4SfSZYWRgyS8uaXk.eyJlbWF
pbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0
LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xODYxLWUyMTEtYmIyMC1iN
GZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMDFiMjgwOTI1ZSIsImlzc3
VlZF9hdCI6IjEzNTg0NzY4NTciLCJ2ZXIiOiIxIn0&emailMessageId=6ced6f75-1861-e211-8620-
f28df699edf6&emailType=Invite&emailLinkType=ProfileName&sdate=201301180240&utm_so
urce=EmailInvite&utm_medium=Email>

Invite sent: 18 January, 2013

Continue
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=15_11_12_
Eddie_emailLanding_InviteContact_a&emailTemplate=email_InviteContact_a&emailTheme
=30_10_12_Eddie_email_InviteContact_a_InviteContact&user=0f519f62-1861-e211-bb20-
b4fd0eafa145&signedParameters=PzyrEfS-FgEOx0vDmiZpACdfnqs4SfSZYWRgyS8uaXk.eyJlbWF
pbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0
LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xODYxLWUyMTEtYmIyMC1iN
GZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMDFiMjgwOTI1ZSIsImlzc3
VlZF9hdCI6IjEzNTg0NzY4NTciLCJ2ZXIiOiIxIn0&emailMessageId=6ced6f75-1861-e211-8620-
f28df699edf6&emailType=Invite&emailLinkType=MainCallToAction&sdate=201301180240&u
tm_source=EmailInvite&utm_medium=Email>

reply@reply.github.com
 was invited to join SkillPages by Qaiser Abbas. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=5xwqHjVTS18rEUE
ZX1grMmQK3Hab-WNHVwVX5_upywc.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2
ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImlzc3VlZ
F9hdCI6IjEzNTg0NzY4NTciLCJ2ZXIiOiIxIn0&emailMessageId=6ced6f75-1861-e211-8620-f28
df699edf6&emailType=Invite&emailLinkType=Unsubscribe&sdate=201301180240&utm_sourc
e=EmailInvite&utm_medium=Email> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by qaiser110** [comment]
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
Eddie_emailLanding_InviteContact_a_firstreminder&emailTemplate=email_InviteContac
t_a&emailTheme=06_09_12_Eddie_email_InviteContact_a_FirstInvitationReminder&user=
0f519f62-1861-e211-bb20-b4fd0eafa145&signedParameters=UsopsWTORJOktoDcjL_oEOFhzSj
5D2DYpIh544-W308.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVl
ZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2M
i0xODYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLW
IzMDFiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTkwNzQ2MTciLCJ2ZXIiOiIxIn0&emailMessageId=
73561f3f-8866-e211-b51b-c9754295e69f&emailType=InviteFirstReminder&sdate=20130125
0043&utm_source=EmailInviteFirstReminder&utm_medium=Email&emailLinkType=Logo>

Hi,

Unlock new opportunities for you and your contacts.

<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
Eddie_emailLanding_InviteContact_a_firstreminder&emailTemplate=email_InviteContac
t_a&emailTheme=06_09_12_Eddie_email_InviteContact_a_FirstInvitationReminder&user=
0f519f62-1861-e211-bb20-b4fd0eafa145&signedParameters=UsopsWTORJOktoDcjL_oEOFhzSj
5D2DYpIh544-W308.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVl
ZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2M
i0xODYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLW
IzMDFiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTkwNzQ2MTciLCJ2ZXIiOiIxIn0&emailMessageId=
73561f3f-8866-e211-b51b-c9754295e69f&emailType=InviteFirstReminder&sdate=20130125
0043&utm_source=EmailInviteFirstReminder&utm_medium=Email&emailLinkType=ProfileTh
umb>

Qaiser Abbas
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
Eddie_emailLanding_InviteContact_a_firstreminder&emailTemplate=email_InviteContac
t_a&emailTheme=06_09_12_Eddie_email_InviteContact_a_FirstInvitationReminder&user=
0f519f62-1861-e211-bb20-b4fd0eafa145&signedParameters=UsopsWTORJOktoDcjL_oEOFhzSj
5D2DYpIh544-W308.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVl
ZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2M
i0xODYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLW
IzMDFiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTkwNzQ2MTciLCJ2ZXIiOiIxIn0&emailMessageId=
73561f3f-8866-e211-b51b-c9754295e69f&emailType=InviteFirstReminder&sdate=20130125
0043&utm_source=EmailInviteFirstReminder&utm_medium=Email&emailLinkType=ProfileNa
me>

Invite sent: 18 January, 2013

Join me on SkillPages
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
Eddie_emailLanding_InviteContact_a_firstreminder&emailTemplate=email_InviteContac
t_a&emailTheme=06_09_12_Eddie_email_InviteContact_a_FirstInvitationReminder&user=
0f519f62-1861-e211-bb20-b4fd0eafa145&signedParameters=UsopsWTORJOktoDcjL_oEOFhzSj
5D2DYpIh544-W308.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVl
ZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2M
i0xODYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLW
IzMDFiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTkwNzQ2MTciLCJ2ZXIiOiIxIn0&emailMessageId=
73561f3f-8866-e211-b51b-c9754295e69f&emailType=InviteFirstReminder&sdate=20130125
0043&utm_source=EmailInviteFirstReminder&utm_medium=Email&emailLinkType=MainCallT
oAction>

reply@reply.github.com
 was invited to join SkillPages by Qaiser Abbas. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=FaJxiie0KsPE-Yv
9C7pnddLkaqakhRoHCQ_U8LMZTmU.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2
ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImlzc3VlZ
F9hdCI6IjEzNTkwNzQ2MTciLCJ2ZXIiOiIxIn0&emailMessageId=73561f3f-8866-e211-b51b-c97
54295e69f&emailType=InviteFirstReminder&sdate=201301250043&utm_source=EmailInvite
FirstReminder&utm_medium=Email&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.

**Comment by qaiser110** [comment]
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
emailLanding_InviteContact_a_secondreminder&emailTemplate=email_InviteContact_a&e
mailTheme=06_09_12_Eddie_email_InviteContact_a_SecondInvitationReminder&user=0f51
9f62-1861-e211-bb20-b4fd0eafa145&signedParameters=CvrE80ErBm2HgyUCnHNFW0ng4pjp_-X
ZWkqu8r4oOcY.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1
ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xO
DYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMD
FiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTk2Nzg5NTgiLCJ2ZXIiOiIxIn0&emailMessageId=3b5b
d455-076c-e211-b51b-c9754295e69f&emailType=InviteSecondReminder&sdate=20130201003
5&utm_source=EmailInviteSecondReminder&utm_medium=Email&emailLinkType=Logo>

Hi,

Unlock new opportunities for you and your contacts.

<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
emailLanding_InviteContact_a_secondreminder&emailTemplate=email_InviteContact_a&e
mailTheme=06_09_12_Eddie_email_InviteContact_a_SecondInvitationReminder&user=0f51
9f62-1861-e211-bb20-b4fd0eafa145&signedParameters=CvrE80ErBm2HgyUCnHNFW0ng4pjp_-X
ZWkqu8r4oOcY.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1
ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xO
DYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMD
FiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTk2Nzg5NTgiLCJ2ZXIiOiIxIn0&emailMessageId=3b5b
d455-076c-e211-b51b-c9754295e69f&emailType=InviteSecondReminder&sdate=20130201003
5&utm_source=EmailInviteSecondReminder&utm_medium=Email&emailLinkType=ProfileThum
b>

Qaiser Abbas
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
emailLanding_InviteContact_a_secondreminder&emailTemplate=email_InviteContact_a&e
mailTheme=06_09_12_Eddie_email_InviteContact_a_SecondInvitationReminder&user=0f51
9f62-1861-e211-bb20-b4fd0eafa145&signedParameters=CvrE80ErBm2HgyUCnHNFW0ng4pjp_-X
ZWkqu8r4oOcY.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1
ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xO
DYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMD
FiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTk2Nzg5NTgiLCJ2ZXIiOiIxIn0&emailMessageId=3b5b
d455-076c-e211-b51b-c9754295e69f&emailType=InviteSecondReminder&sdate=20130201003
5&utm_source=EmailInviteSecondReminder&utm_medium=Email&emailLinkType=ProfileName


Invite sent: 18 January, 2013

Join me on SkillPages
<http://www.skillpages.com/i/landing/emailLanding_InviteContact_a?theme=18_10_12_
emailLanding_InviteContact_a_secondreminder&emailTemplate=email_InviteContact_a&e
mailTheme=06_09_12_Eddie_email_InviteContact_a_SecondInvitationReminder&user=0f51
9f62-1861-e211-bb20-b4fd0eafa145&signedParameters=CvrE80ErBm2HgyUCnHNFW0ng4pjp_-X
ZWkqu8r4oOcY.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2ODM1ZmUwMzVlZDc1
ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImZyb20iOiIwZjUxOWY2Mi0xO
DYxLWUyMTEtYmIyMC1iNGZkMGVhZmExNDUiLCJ0byI6IjZjN2NmNzkzLTJjNTAtNWFmMi1iNTRiLWIzMD
FiMjgwOTI1ZSIsImlzc3VlZF9hdCI6IjEzNTk2Nzg5NTgiLCJ2ZXIiOiIxIn0&emailMessageId=3b5b
d455-076c-e211-b51b-c9754295e69f&emailType=InviteSecondReminder&sdate=20130201003
5&utm_source=EmailInviteSecondReminder&utm_medium=Email&emailLinkType=MainCallToA
ction>

reply@reply.github.com
 was invited to join SkillPages by Qaiser Abbas. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=2WGpHEkNtvCLtgJ
nzVesiAv2POLNSFPBEL2Ezz52XwU.eyJlbWFpbCI6InJlcGx5K2ktODM5MTg3My1mY2FkMjBlNTM3OTI2
ODM1ZmUwMzVlZDc1ZjBkMjIxOTgxNTNhMmM0LTIyNTM4NDdAcmVwbHkuZ2l0aHViLmNvbSIsImlzc3VlZ
F9hdCI6IjEzNTk2Nzg5NTgiLCJ2ZXIiOiIxIn0&emailMessageId=3b5bd455-076c-e211-b51b-c97
54295e69f&emailType=InviteSecondReminder&sdate=201302010035&utm_source=EmailInvit
eSecondReminder&utm_medium=Email&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.
