### ISSUE TITLE
Ajax loading spinner is visible on the right side of all pages

### ISSUE THREAD

**Issue by stowball** [darkwing/blog#39]
Tested on Android 4.0.3's Browser, Chrome & Firefox.

Screenshot: http://db.tt/l69qpDQ5

**Comment by darkwing** [comment]
This is desired :)

**Comment by reitermarkus** [comment]
But it doesn't even load nor rotate.

**Comment by darkwing** [comment]
It's there as a global indicator;  grey and static when nothing is happening, blue and spinning when something is.

**Comment by reitermarkus** [comment]
Oh ok. I think my Internet is too fast because I haven't seen the blue one yet. ^^

**Comment by darkwing** [comment]
That means my site is fast...YESSSSSSSS :)

**Comment by reitermarkus** [comment]
Or that. =)
