### ISSUE TITLE
Guest Post Broken Link

### ISSUE THREAD

**Issue by njenney** [darkwing/blog#4]
Articles > Submit Guest Post 

Result: 404 error -- http://davidwalsh.name/guest-post

**Comment by darkwing** [comment]
Was written but not publically published.  Fixed.  Thank you!

**Comment by njenney** [comment]
Cool, nice job, I will let you know if I find anything else.
 

Neal P. Jenney
njenney@yahoo.com
http://twitter.com/njenney
