### ISSUE TITLE
arrow key flyouts stay open

### ISSUE THREAD

**Issue by matthewlein** [darkwing/blog#7]
After hitting an arrow key left or right, you see the next/prev post. If you are not interested, there is no way to close that and continue reading. On scroll or timeout might make sense.

**Comment by darkwing** [comment]
Good point, I have an idea of how to fix this.  Thanks for the report!

**Comment by darkwing** [comment]
Sweet, went with timeout.  Thanks Matthew!  Should be up shortly!
